### ISSUE TITLE
swift4, xcode 9.2 errors

### ISSUE THREAD

**Issue by gaming-hacker** [JustHTTP/Just#101]
hi,
i get the following errors

> Cannot convert return expression of type 'Dictionary<Key, Value>.Values' to return type 'LazyMapCollection<[Key : Value], Value>'

lines 330-333

```
  public var keys: LazyMapCollection<[Key : Value], Key> {
    return _data.keys
  }
  public var values: LazyMapCollection<[Key : Value], Value> {
    return _data.values
  }
```

i didn't see the "values" being used anywhere??  i commented out the lines and checked a couple of files and servers and got back the correct GET/POST

**Comment by goribchat** [comment]
is Just supported for swift 4.0?

**Comment by juzhizhang** [comment]
public var keys:Dictionary<Key,Value>.Keys {
    return _data.keys
  }
    public var values:Dictionary
        <Key,Value>.Values {
    return _data.values
  }

change, is ok!

**Comment by EnlightenedCSF** [comment]
@juzhizhang create a PR with relevant changes, please.

**Comment by gaming-hacker** [comment]
check to see if you have synced the thread back on the main thread and update the gui

**Comment by goribchat** [comment]
Okay Thanks
