### ISSUE TITLE
Just is giving code -1001

### ISSUE THREAD

**Issue by goribchat** [JustHTTP/Just#106]
When i uploading an image to server with the help of this code 
Just.post(
    "http://justiceleauge.org/member/register",
    data: ["username": "barryallen", "password":"ReverseF1ashSucks"],
    files: ["profile_photo": .URL(fileURLWithPath:"flash.jpeg", nil)]
) { r in
    if r.ok { /* success! */ }
}
it is showing error code -1001. pleasehelp regarding this matter

**Comment by dduan** [comment]
That URL does not exist in reality. `-1001` can mean a lot of things but usually it's a server problem.
