### ISSUE TITLE
Just.get params always return string Optional

### ISSUE THREAD

**Issue by irfanpule** [JustHTTP/Just#109]
I update xcode 10 and recompile carthage packages use Swift 4.2. After recompile any problem in Just.get when I use args `params`:

Ex:
```
let params: [String: String] = [
    'session_key': Session.key!
]

Just.get(url, params: params) { response in
```
request always invalid session_key to server. Then I look access.log, I found query string use `Optional`
ex: `?session_key=Optional%28%2276jqfaeq94ar02boscaie91idbq6e0hz%22%29`

**Comment by dduan** [comment]
[fixed](https://github.com/JustHTTP/Just/commit/9825b031a3a416fb04c23aef7c38107f36b5126c) in 0.7.0. Thanks for reporting!
