### ISSUE TITLE
Just.framework missing CFBundleVersion when uploading

### ISSUE THREAD

**Issue by j-elmer123** [JustHTTP/Just#112]
This only happens if I use the 0.7.0 version.

More Info:
- XCode 10
- iOS App

![screen shot 2018-09-27 at 12 00 52 pm](https://user-images.githubusercontent.com/8566597/46124354-d2d14300-c24d-11e8-84cd-639246397616.png)

**Comment by dduan** [comment]
hi @j-elmer123. Are you using Carthage or CocoaPods?

**Comment by j-elmer123** [comment]
> hi @j-elmer123. Are you using Carthage or CocoaPods?

Hi @dduan 
I'm using Carthage

**Comment by j-elmer123** [comment]
sorry, forgot to add more info.
Yes I am using Xcode 10 and for iOS app

**Comment by dduan** [comment]
@j-elmer123 I've fixed the issue. Please clear your Carthage cache and build again. Thanks for reporting.

**Comment by dduan** [comment]
Thanks for reporting! I've also released 0.7.1 which should more permanently fix this.
