### ISSUE TITLE
how to set JSON array for the json request body

### ISSUE THREAD

**Issue by ruiyang2012** [JustHTTP/Just#13]
the signature for ajax call's json body is [String:AnyObject?], I need to post a JSON array to the server, how can I do that, will JustHTTP support that use case?

**Comment by dduan** [comment]
@ruiyang2012 the signature is `[String:AnyObject]?`, different from what you posted. 

Unfortunately, there's no convenient way to send an JSON array. The `requestBody` parameter allows you to construct the request body directly, so you can send your JSON array this way:

```swift
if let body = try? NSJSONSerialization.dataWithJSONObject([1,2,3], options: NSJSONWritingOptions(rawValue: 0)) {
    Just.post("http://httpbin.org/post", headers:["content-type":"application/json"], requestBody: body)
}
```

There might be a case to change the type of `json` here. I'll need to see how common the use case such as yours is.
