### ISSUE TITLE
Using Swift 2 doesn't seem to like Just

### ISSUE THREAD

**Issue by DiogoNeves** [JustHTTP/Just#14]
I got these build issues, any ideas? I'm new to Swift and Xcode and need some help :smile: 
![screenshot 2015-09-03 11 54 45](https://cloud.githubusercontent.com/assets/178898/9656747/bdad1500-5232-11e5-90c5-1f99f0716584.png)

.../Pods/Just/Just/Just.swift:116:23: Expected expression in 'return' statement
.../Pods/Just/Just/Just.swift:748:35: Expected expression in assignment
.../Pods/Just/Just/Just.swift:753:43: Expected expression in assignment
.../Pods/Just/Just/Just.swift:257:22: Use of undeclared type 'LazyMapCollection'
.../Pods/Just/Just/Just.swift:260:24: Use of undeclared type 'LazyMapCollection'
.../Pods/Just/Just/Just.swift:163:21: '[String]' does not have a member named 'forEach'
.../Pods/Just/Just/Just.swift:634:13: '[(String, String)]' does not have a member named 'appendContentsOf'
.../Pods/Just/Just/Just.swift:647:47: '[String]' does not have a member named 'joinWithSeparator'

**Comment by dduan** [comment]
@DiogoNeves please use the latest Xcode beta (Xcode 7 beta 6 as of right now).

**Comment by DiogoNeves** [comment]
I am. Although, I noticed the Pods framework has iOS 8 as a target, do I need to change that?
Thanks
