### ISSUE TITLE
How to cancel http request?

### ISSUE THREAD

**Issue by chenjsa** [JustHTTP/Just#16]
If i do Just.Post(), how can i cancel the post request?

**Comment by Instigater** [comment]
Get a new queue from GCD and perform your HTTP request in this queue via either `dispatch_sync` or `dispatch_async` function. During the progress you can suspend this queue immediately with `dispatch_suspend` function.

More information on: http://stackoverflow.com/questions/6737044/suspending-gcd-query-problem/6737719#6737719

For the record, I didn't try the solution I offer. Emanating from the analogy of GCD, it should work without any flaw.

Do not hesitate to ask if you have another question.

**Comment by chenjsa** [comment]
I mean the NSURLSessionTask.cancel() method.

**Comment by Instigater** [comment]
No difference IMO, however it's better to listen `deinit` methods of variables in order to catch ARC flaw, if any.

**Comment by chenjsa** [comment]
With the AFNetworking i put all the request into an array in view controller. If the view controller disappear, i will call request.cancel() to cancel all http request. I decide to try just because it's lighter than Alamofire, but i can't find the NSURLSessionTask object in this framework.

**Comment by Instigater** [comment]
If you are not multi-threading, the option I had gave you might be a logical solution (and even more optimized if you implement it properly).

By the way, it's not good way to make HTTP requests in a view controller. View controllers control view, they do not do anything else about data. That should be done by your model object(s), afterwards you can pass the data via various methods.

**Comment by chenjsa** [comment]
Yes, I just return the request object to view controller for cancel.

**Comment by dduan** [comment]
@chenjsa

This is something that's not directly supported currently. 

In NSURLSession (on which all AFNetworking 2, Alamofire as well as Just are based), the `cancel()` method is merely a "suggestion". The request could still be sent after `cancel()`, but delegate methods and callbacks will not be fired for the responses. This is why the ideal way to "cancel" a network request is to not make it in the first place. @Instigater 's provided an excellent way to implement this.

In reality, managing with GCD or NSOperationQueue can get rather complex quickly. Just should expose the [task object](https://github.com/JustHTTP/Just/blob/swift-2.0/Just/Just.swift#L840) somehow in the near future.

**Comment by chenjsa** [comment]
Thank you!
