### ISSUE TITLE
Module file was created by a newer version of the compiler

### ISSUE THREAD

**Issue by bobanda87** [JustHTTP/Just#17]
I am using XCode6.4 and I imported JustHTTP/Just library using Carthage. (*** Downloading Just at "v0.3")

Import worked fine and here is a screenshot of my xcodeproj file enter image description here
![screen shot 2015-09-08 at 11 34 37 pm](https://cloud.githubusercontent.com/assets/5786123/9748143/e9f0902a-5682-11e5-90cb-3c623e2d49bb.png)

But on this line:

```
import Just
```

I am getting this error

```
Module file was created by a newer version of the compiler
...../Carthage/Build/iOS/Just.framework/Modules/Just.swiftmodule/x86_64.swiftmodule
```

Can someone advice? Thanks!

**Comment by dduan** [comment]
The default branch (v0.3) is on Swift 2. So you should ether switch to Xcode 7 or use `github "JustHTTP/Just" ~> v0.1` in your Cartfile.
