### ISSUE TITLE
about the playground

### ISSUE THREAD

**Issue by ZsIsMe** [JustHTTP/Just#18]
Thanks for your great job! I have a problem about the playground.
the playground provided in this project just use for reading?
We can't run the playground to see the result,right?

**Comment by dduan** [comment]
@ZsIsMe Hi, all the code in the playground should actually run with Xcode 7. 

The GM seems to have introduced a bug where you have to click on Just.swift from the Sources folder, then switch back to the playground.

With these steps, you'll see the sample code gets executed and you can start play with them.

I think I'm going to file a radar for this.

**Comment by dduan** [comment]
@ZsIsMe fixed. Download the playground again and it'll start running with Xcode 7 GM.

**Comment by dduan** [comment]
@ZsIsMe thanks for reporting this. I can't find the root cause. Must be some quirky playground file behavior created from Xcode betas.
