### ISSUE TITLE
Created with older version of the compiler [Error]

### ISSUE THREAD

**Issue by esafwan** [JustHTTP/Just#21]
I am getting an error saying the `Module file was created using older version of the compiler; rebuild 'Just' and try again: ...`

What to do?

**Comment by dduan** [comment]
Hey @esafwan, I'm sorry this didn't work for you. I've released a new version since you posted the question. Would you mind trying it again?

If you used Carthage, please make sure you remove `~> 0.1` for Just.

Let me know if this still doesn't work for you.
