### ISSUE TITLE
Custom headers?

### ISSUE THREAD

**Issue by raulriera** [JustHTTP/Just#23]
Hey 😬
I can see through the code that indeed the library support custom headers, anywhere you can point me in the docs for it? Can't seem to find anything

**Comment by dduan** [comment]
like this?

```swift
Just.get("http://httpbin.org/get", headers:["Content-Type": "Swift is Sweet"])
```

**Comment by raulriera** [comment]
Yeah hehe, found it after I wrote it... anywhere to set this as defaults? Trying to pass around the Authorisation Bearer into all the requests.

**Comment by raulriera** [comment]
Mostly trying to replicate this, where I funnel all the requests into a single thing that adds anything I need

```swift
if let oAuthToken = token {
            request.addValue("Bearer \(oAuthToken.code)", forHTTPHeaderField: "Authorization")
        }
                
        NSURLSession.sharedSession().dataTaskWithRequest(request) { (data, response, error) in
```

Closing as this is only a question

**Comment by dduan** [comment]
@raulriera I made a new release to address this [0.4.3](https://github.com/JustHTTP/Just/releases/tag/v0.4.3)

😀

**Comment by raulriera** [comment]
That is awesome! thanks :dancer:

**Comment by raulriera** [comment]
Hey, quick follow up... after the new release I am unable to use it with carthage

```
*** Checking out AuthenticationViewController at "1.1.0"
*** Checking out Decodable at "v0.3.3"
*** Checking out Locksmith at "2.0.3"
*** Downloading Just at ""
```

For some reason the tag shows as "", have you seen this before?

**Comment by raulriera** [comment]
Bah, I am full of fails lately hehe... upgrading carthage and git worked
