### ISSUE TITLE
Clear basic auth credentials

### ISSUE THREAD

**Issue by igorpan** [JustHTTP/Just#24]
It seems that Just records credentials with ".ForSession" persistence. 

Is there a way I can clear these? Ideally, can I make it use "NSURLCredentialsPersistence.None"?

**Comment by dduan** [comment]
@igorpan this is possible now in version [0.4.4](https://github.com/JustHTTP/Just/releases/tag/v0.4.4).

**Comment by igorpan** [comment]
@dduan That is awesome! Great job!
