### ISSUE TITLE
Possible to POST an array of files?

### ISSUE THREAD

**Issue by lauritzsh** [JustHTTP/Just#32]
Hi, I am wondering if it is possible to POST an array of files in a single request? The server expects a field called `files[]` or just `files` that is supposed to be an array of files. Is it possible to do this in any way? I can only figure out how to post a single file.

I tried `let files: AnyObject = [/* my HTTPFiles */]` but that does not work, because array literal can't be used for AnyObject.

The files I am trying to upload is using multipart/form-data.

Thank you.

**Comment by dodekeract** [comment]
You might be able to use base64 encoding for this, otherwise you probably have to use a custom protocol, which I'd avoid.

Not sure if HTTP2 would be able to do this though.

**Comment by penacristian** [comment]
Any update on this issue?
