### ISSUE TITLE
Plus symbol "+" should be percent encoded as '%2B' in form data

### ISSUE THREAD

**Issue by mariotaku** [JustHTTP/Just#38]
Current version left '+' unchanged, which causes server treats '+' as ' '.

https://www.w3.org/TR/html4/interact/forms.html#h-17.13.4.1

https://url.spec.whatwg.org/#urlencoded-serializing

**Comment by dduan** [comment]
Fixed in version 0.4.8: https://github.com/JustHTTP/Just/releases/tag/v0.4.8

Thank you @mariotaku!
