### ISSUE TITLE
Can't build with Xcode 8 Beta 6

### ISSUE THREAD

**Issue by randyhill** [JustHTTP/Just#41]
I'm trying to use Just in an iOS 10 message extension. Due to various issues, Cocoapods isn't working for me, so I've tried dropping in Just.swift, but I get a whole mess of compile errors, some I don't feel confident about fixing. 

Has Swift 3 syntax changed since your last build?

**Comment by randyhill** [comment]
One example

    public lazy var headers:CaseInsensitiveDictionary<String,String> = {
        return CaseInsensitiveDictionary<String,String>(dictionary: (self.response as? HTTPURLResponse)?.allHeaderFields as? [String:String] ?? [:])
    }()

produces the error Expression type '[String : String]? is ambiguous without more context, on the return line.

**Comment by randyhill** [comment]
This works...
    public lazy var headers:CaseInsensitiveDictionary<String,String> = {
        if let httpResponse = self.response as? HTTPURLResponse {
            let headerFieldsDict = httpResponse.allHeaderFields as NSDictionary? as? [String:String]
            return CaseInsensitiveDictionary<String,String>(dictionary: headerFieldsDict ?? [:])
        }
        return [:]
    }()

https://forums.developer.apple.com/message/169819#169819

**Comment by randyhill** [comment]
I have fixed all the other compile errors, will try to check in my version to you after I see if it works.

**Comment by dduan** [comment]
Thank you. Master should work with Xcode 8 GM now.
