### ISSUE TITLE
should methods have @ discardableResult attribute?

### ISSUE THREAD

**Issue by alcamla** [JustHTTP/Just#42]
In the cases where the operations (put, post, etc) are performed asynchronously, the result is ignored and the manipulation of  the result is done  in the completion handler. Currently this warning must be silenced manually, but I wonder if the @ discardableResult could be used instead.

**Comment by dduan** [comment]
Ah, great catch. Thank you!

**Comment by dduan** [comment]
Done in release 0.5.1.
