### ISSUE TITLE
Something wrong with timeout.

### ISSUE THREAD

**Issue by xjbeta** [JustHTTP/Just#43]
I want to use 'get' for urls in a array. (count maybe > 100)

`[urls].foreach {
    Just.get($0, timeout: 1) {
        ...
    }
}`

All the 'get' will finish in 1 second, the timeout isn't set to each 'get'.

Vsersion: 0.5.1
Xcode: 8  (8A218a)
Swift: 3.0

**Comment by dduan** [comment]
Hi @xjbeta,

I'm not sure what to make of your report. For a test, I ran

```swift
import XCPlayground
import Foundation
["http://httpbin.org", "https://google.com"].forEach {
  let start = Date()
  Just.get($0, timeout: 1) { r in
    print(start.timeIntervalSinceNow)
  }
}
```

The printouts looks normal (less than a second). If the request takes more than 1 second, it should fail  after the first second. Does this match your observation?

**Comment by xjbeta** [comment]
thanks for answer
