### ISSUE TITLE
carthage update fails 

### ISSUE THREAD

**Issue by raghvendra** [JustHTTP/Just#44]
Hi,

carthage update with "0.5.2" version fails with following command - 

A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/xyz/projects/project-name/Carthage/Checkouts/Just/Externals/Quick/Quick.xcworkspace -scheme Quick-OSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:

Why is it building Quick?

How to get past this error?

Thanks!

**Comment by dduan** [comment]
@raghvendra try deleting the `Carthage` folder.
