### ISSUE TITLE
Asynchronous Callback

### ISSUE THREAD

**Issue by aguel** [JustHTTP/Just#46]
My app crashing using asynchronous callback but works fine when switching to synchronous mode. I dont know why.

Pseudo Sample:
APP CRASHING:
Just.post(
    "http://justiceleauge.org/member/register",
    data: ["username": "barryallen", "password":"ReverseF1ashSucks"],
    files: ["profile_photo": .URL(fileURLWithPath:"flash.jpeg", nil)]
) { r in
    if r.ok { /* SOME CODE HERE! */ }
}

THIS WORKS:
let r = Just.post(
    "http://justiceleauge.org/member/register",
    data: ["username": "barryallen", "password":"ReverseF1ashSucks"],
    files: ["profile_photo": .URL(fileURLWithPath:"flash.jpeg", nil)]
) 

if r.ok { /* SOME CODE HERE! */ }

**Comment by JustHTTP** [comment]
Can you provide back trace? Pseudo code is not helpful since it's not crashing for anybody else.

Daniel Duan

**Comment by rsardek** [comment]
NSURLSession has some asserts that if not respected by your code will yield crash. For example, use of asynchronous upload methods (with completion handler) in a background NSURLSession configuration.

**Comment by aguel** [comment]
Do you have any sample code? The documentation provides only simple example. Thanks.

**Comment by sravanco** [comment]
I had a crash with asynchronous callback saying that Im updating UI in background thread. As in the Note given [here](http://docs.justhttp.net/QuickStart.html), I have to dispatch UI update to main thread. Great if callback is already wrapped into main queue by JustHTTP.
```
DispatchQueue.main.async {
    Update UI here.
}
```

**Comment by JustHTTP** [comment]
Just can't wrap callback for you because lots of times that's not what user needs. You'll find after a net working call, there's more work to do  (processing things you just downloaded, for example) before you need to update UI.

This is also the design decision made by Apple with NSURLSession.

Daniel Duan
