### ISSUE TITLE
Just with baseUrl

### ISSUE THREAD

**Issue by hashemp206** [JustHTTP/Just#49]
it seems for every network request I need to rewrite baseUrl. so it is a way to have a shared `Just` with a base url?

**Comment by dduan** [comment]
There's nothing to prevent you from creating your own abstraction. Base URL is not a problem a network library should solve.

**Comment by hashemp206** [comment]
you are right, but simplicity and reducing boilerplate code (as I see in Just) is most important aspect of developing a framework.

can your provide simple solution of how can I write this layer?
