### ISSUE TITLE
Carthage error

### ISSUE THREAD

**Issue by Lufthummel** [JustHTTP/Just#62]
Hi, I can't build the project with Carthage:

A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/hkremmin/devel/IOS/GSimpleRelease/Carthage/Checkouts/Just/Just.xcworkspace -scheme Just-OSX -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme Just-OSX is not currently configured for the clean action.

Carthage version is 0.18.1
OSX 10.12.1
XCode 8.1

Build command is 
carthage update --platform ios

**Comment by dduan** [comment]
I can't reproduce this with same setups. Would you mind trying again after deleting the `Carthage` folder?

**Comment by Lufthummel** [comment]
That fixed the issue, thanks!
