### ISSUE TITLE
macOS - image not found - Just Frameowrk

### ISSUE THREAD

**Issue by rustymagnet3000** [JustHTTP/Just#63]
Why does the following macOS setup give a JustHTTP linker error ?

Steps to recreate linker error:

    Create new macOS Command Line app
    Run pod init from Terminal
    Update the podfile with the below

platform :osx, ’10.10’
use_frameworks!

target 'MyApp' do
  pod 'Just'
end

    Run pod install
    Open and Build workspace
    Error: dyld: Library not loaded: @rpath/just.framework
    Reason: image not found

AT THIS POINT, this error makes sense. You need to go to the Target's / General / Linked Frameworks and Libraries. Then add Just. 

Build and run. Same error. Why?

A short summary of what has been tried:

    checked developer cert was valid
    checked Path of the Just framework pointed to Relative to build products / Projects / Product
    Tried manually pulling in project,  git submodule, carthage and cocoapods
    Deleted Derived Data
    Added Runtime Search Path $(inherited) @executable_path/Frameworks

**Comment by JustHTTP** [comment]
IIRC, Command Line Apps can't use any dynamic frameworks because the latter requires the construct of a "bundle" to exist. I recommend embedding the source file to your command line app.

Daniel Duan

**Comment by rustymagnet3000** [comment]
@dduan thank you!  That was it.  I just dragged your just.swift file into my workspace, compiled and now I can send Just requests.

Let me know if I can return the favor in anyway.
