### ISSUE TITLE
How to send a request body as this example?

### ISSUE THREAD

**Issue by moumitachina** [JustHTTP/Just#70]
Equivalent Android code is this:

public static void sendPushNotificatonToFirebaseServer(FirebaseNoti firebaseNoti) {
    final String KEY = "AAAA7l6A1jI:APA91bH2oUNSdtifz3qE9RAynqSEa3JgkXARdH6tD_3S8cm9--cSU5Qz0-zfgVQ2aTnYWvsypmZv0mMXUBxqa6R8i14sgMeW0HF2B3WlEFRstdQ3HXrvES9mUZk8YfXr82gLEDC8uGQD";
    String json = App.gson.toJson(firebaseNoti);
    Log.e("SendingPushJSON", json);
    RequestBody body = RequestBody.create("application/json; charset=utf-8", json);
    final Request request = new Request.Builder()
            .url("https://fcm.googleapis.com/fcm/send")
            .post(body)
            .addHeader("Authorization", "key="+KEY)
            .addHeader("Content-Type", "application/json")
            .build();

    if (Looper.myLooper() == Looper.getMainLooper()) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                executeRequest(request);
            }
        }).start();
    } else {
        executeRequest(request);
    }
}

**Comment by tuyuri2201** [comment]
i meet the same problem

**Comment by moumitachina** [comment]
Thanks for replying, I have solved this using this. 
      
 let json = model.toJSONString()!
let data = json.dataUsingEncoding(NSUTF8StringEncoding)!
Just.post(url, headers: header , requestBody : data ) { r in
}
