### ISSUE TITLE
Xcode 9 beta 3 error

### ISSUE THREAD

**Issue by raffaelps** [JustHTTP/Just#87]
When I run, these error occurs:

Cannot convert return expression of type 'Dictionary<Key, Value>.Keys' to return type 'LazyMapCollection<[Key : Value], Key>'

Cannot convert return expression of type 'Dictionary<Key, Value>.Values' to return type 'LazyMapCollection<[Key : Value], Value>'

**Comment by xhp281** [comment]
mee to

**Comment by xhp281** [comment]
@raffaelps https://github.com/JustHTTP/Just/pull/83/commits/d6db9379a30975d6bab99fa05275b93a4fe691ad

**Comment by xhp281** [comment]
@raffaelps https://github.com/JustHTTP/Just/pull/83/commits/d6db9379a30975d6bab99fa05275b93a4fe691ad this is ok

**Comment by PritiKumr** [comment]
How can I use this in my Podfile? @xhp281 Thanks :)

**Comment by xhp281** [comment]
@PritiKumr  if you use xcode9 you can change 'LazyMapCollection<[Key : Value], Key>' to 'Dictionary<Key, Value>.Keys'.   if use xcode8.3.3 is ok .my english is not ok, i dont no if you can understand what I mean.

**Comment by dduan** [comment]
you can use the `swift-4` branch now.
